### ISSUE TITLE
Please tag the 0.0.5 release

### ISSUE THREAD

**Issue by xtaran** [tpneill/wml-tools#1]
According to the changelog, there is a 0.0.5 release now. Could you please at least tag the release accordingly so that it shows up on https://github.com/tpneill/wml-tools/releases or https://github.com/tpneill/wml-tools/tags?

`git tag 0.0.5 && git push --tags`should do it, if git HEAD refers to the release.

Thanks in advance!

And thanks for making it finally truely free software! :-)

**Comment by tpneill** [comment]
Done!
